### Envoi du code de vérification par email
POST http://localhost:3000/auth/send-verification-email
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com"
}

### Vérification du code de l'email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com",
  "code": "957489"
}


### Création du mot de passe après vérification de l'email
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com",
  "password": "Password123"
}

### Connexion de l'utilisateur
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mickael.4870@gmail.com",
  "password": "Password123"
}

### Recherche SIREN
POST http://localhost:3000/validate-business-info
Content-Type: application/json

{
  "sirenOrSiret": "930735865"
}

### Envoyer 0.1 SOL de l'expéditeur au destinataire
POST http://localhost:3000/solana/directPayment
Content-Type: application/json

{
  "senderPrivateKey": [47,235,250,47,65,84,201,207,39,80,161,11,155,178,143,20,70,185,49,181,247,133,102,225,251,32,69,211,62,99,189,5,14,21,14,60,143,24,205,127,111,78,153,18,16,86,112,214,111,47,210,16,239,229,53,76,159,1,236,99,229,72,84,216],
  "senderPublicKey": "wyL7JG3mDey2cMCSkzSC3G2Tc7yPDHz87UTGzJV8bbd",
  "recipientPublicKey": "BMntwkUHDo5bHrVffV1NVLdZpGpm8nYguHfBcgpy558T",
  "amount": 3,
  "asset": "SOL"
}


### Vérifier l'historique de transaction
GET http://localhost:3000/solana/transaction-history/2ED6LdWKr2TftXo6DVniNAaRrS7uRRUfX7mmtphw67fK

### Vérifier le solde
GET http://localhost:3000/solana/get-wallet-balance/2ED6LdWKr2TftXo6DVniNAaRrS7uRRUfX7mmtphw67fK