### Simulateur BNPL
POST http://localhost:3000/bnpl/simulate
Content-Type: application/json

{
    "amount": 1000,
    "months": 6
}

### Créer une vente BNPL
POST http://localhost:3000/bnpl/sale
Content-Type: application/json

{
    "sellerPubKey": "wyL7JG3mDey2cMCSkzSC3G2Tc7yPDHz87UTGzJV8bbd",
    "buyerPubKey": "BK1hRVh4tgUkFSuRDFvLS2n7qCW13EmkiJdhVPUJ1EjW",
    "amount": 3,
    "months": 3
}

### Payer une mensualité BNPL
POST http://localhost:3000/bnpl/payment
Content-Type: application/json

{
    "buyerPrivateKey": [255,165,188,28,132,19,98,139,65,173,172,166,231,117,150,213,160,156,251,137,99,45,235,230,253,101,102,203,101,98,233,132,153,50,28,162,145,68,184,77,192,117,104,96,131,224,105,165,50,182,233,14,6,237,41,82,60,36,167,127,161,249,213,229],
    "saleId": 4
}


### Récupérer les détails d'une vente BNPl
GET http://localhost:3000/bnpl/sale/1

### Récupérer les ventes
GET http://localhost:3000/bnpl/user/wyL7JG3mDey2cMCSkzSC3G2Tc7yPDHz87UTGzJV8bbd/sales

### Télécharger l'échéancier en pdf
GET http://localhost:3000/bnpl/sale/1/schedule/merchant/pdf
