### Envoi du code de vérification par email
POST http://localhost:3000/auth/send-verification-email
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com"
}

### Vérification du code de l'email
POST http://localhost:3000/auth/verify-email
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com",
  "code": "957489"
}


### Création du mot de passe après vérification de l'email
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "moncomptoirsecret@gmail.com",
  "password": "Password123"
}

### Connexion de l'utilisateur
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mickael.4870@gmail.com",
  "password": "Password123"
}

### Recherche SIREN
POST http://localhost:3000/validate-business-info
Content-Type: application/json

{
  "sirenOrSiret": "930735865"
}

### Envoyer 0.1 SOL de l'expéditeur au destinataire
POST http://localhost:3000/solana/directPayment
Content-Type: application/json

{
  "senderPrivateKey": [33,172,70,167,121,140,49,156,30,98,227,135,173,144,196,115,132,250,160,249,158,184,163,80,241,171,215,134,79,71,107,220,220,59,33,219,246,133,81,75,153,147,152,172,186,80,169,7,34,77,126,159,220,214,7,239,178,43,129,80,34,147,44,5],
  "senderPublicKey": "FpgzSe5gk94hpEPhU5xsiovEL2rDJTjjfzKHYbZntr2Y",
  "recipientPublicKey": "98WdSe13pFVVRrWtw2bDN68NttUXcGWcysAicpaLMBS7",
  "amount": 0.5,
  "asset": "SOL"
}


### Vérifier l'historique de transaction
GET http://localhost:3000/solana/transaction-history/FpgzSe5gk94hpEPhU5xsiovEL2rDJTjjfzKHYbZntr2Y

### Vérifier le solde
GET http://localhost:3000/solana/get-wallet-balance/FpgzSe5gk94hpEPhU5xsiovEL2rDJTjjfzKHYbZntr2Y