### Simulateur BNPL
POST http://localhost:3000/bnpl/simulate
Content-Type: application/json

{
    "amount": 1000,
    "months": 6
}

### Créer une vente BNPL
POST http://localhost:3000/bnpl/sale
Content-Type: application/json

{
    "sellerPubKey": "wyL7JG3mDey2cMCSkzSC3G2Tc7yPDHz87UTGzJV8bbd",
    "buyerPubKey": "5pC4zNjNDjzvXLZTM4hCfgtRqBS8a4W6abZXc7Za69Qt",
    "amount": 1,
    "months": 3
}

### Payer une mensualité BNPL
POST http://localhost:3000/bnpl/payment
Content-Type: application/json

{
    "buyerPrivateKey": [223,42,93,97,28,175,21,213,3,132,184,105,3,222,53,252,242,76,24,203,233,38,44,255,252,64,7,236,134,72,79,124,71,133,143,173,124,208,71,66,230,171,150,34,230,202,214,38,60,11,37,131,42,101,175,64,1,248,252,31,74,211,71,97],
    "saleId": 52
}


### Récupérer les détails d'une vente BNPl
GET http://localhost:3000/bnpl/sale/1

### Récupérer les ventes
GET http://localhost:3000/bnpl/user/DVPkw98MCX9yCBQh88wbJ8jd3LjVabo68o7g4sFYaW3S/sales

### Télécharger l'échéancier en pdf
GET http://localhost:3000/bnpl/sale/9/schedule/merchant/pdf
